### ISSUE TITLE
feat: 문자 입력 폼 만들기

### ISSUE THREAD

**Issue by gksderrick** [hk-toss-full/react-teach#4]
### date
2024-09-09

### todo

- [ ] input 박스 만들기 
- [ ] state text 만들기 
- [ ] state의 변경사항 만들기

**Comment by gksderrick** [comment]
개인에 하려던걸..
